# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Neoforge Properties
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.197
loader_version_range=[1,)

## Mod Properties
mod_id=norandomticks
mod_name=No Random Ticks
mod_license=All Rights Reserved
mod_version=0.3-1.21.1
mod_group_id=com.cdxx_lxix.norandomticks
mod_authors=CDXX-LXIX
mod_description=We don't do that over here
mod_icon=icon.png
